### ISSUE TITLE
Specify file type for this to lint?

### ISSUE THREAD

**Issue by slahouchuc-everbridge** [AtomLinter/linter-js-yaml#114]
This isn't an issue as much as it is an enhancement request, but is there a way to specify the file types that trigger this to run? It seems it only works for .yaml files, and I can't find a way for the life of me to specify what file extensions this plugin should watch..

Thanks!

**Comment by Arcanemagus** [comment]
This plugin doesn't know or care about what extension a file has, only whether Atom recognizes it as the YAML language.

You can see how to customize what language Atom associates with a file [here](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).
