### ISSUE TITLE
Add eyaml file-extension

### ISSUE THREAD

**Issue by Hufschmidt** [AtomLinter/linter-js-yaml#129]
Would it be possible to also scan [eyaml](https://github.com/voxpupuli/hiera-eyaml) files?

They are just yaml files with optionally encrypted fields. I can already manually scan them with 

`yamllint some/file/with/encrypted-values.eyaml`

But adding editor-support would be nice. :smile:

**EDIT:** Works also with `js-yaml` of course.

**Comment by Arcanemagus** [comment]
This package doesn't actually depend on the file extension, but rather on Atom recognizing the file as YAML. You can customize this recognition following [these steps](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).
