### ISSUE TITLE
Smart quote detection

### ISSUE THREAD

**Issue by xbmcnut** [AtomLinter/linter-js-yaml#147]
Hi there,

Is there any way to configure this in Atom to detect the misuse of smart quotes? I inadvertently copied something recently that was pasted without the code editor and linter-js-yaml did not pick it up. Example below.

`dahua_preset_tuin: curl --digest -u “admin:password” “http://192.168.4.11/cgi-bin/ptz.cgi?action=start&channel=0&code=GotoPreset&arg1=0&arg2=3&arg3=0`

**Comment by Arcanemagus** [comment]
You'll want to file this on [yaml-js](https://github.com/connec/yaml-js), this is just a wrapper around that.
