### ISSUE TITLE
Improve usage instructions

### ISSUE THREAD

**Issue by spuder** [AtomLinter/linter-js-yaml#15]
It isn't clear in the readme how to use this plugin. Other linters like the json plugin display a notification in the bottom of atom when you `ctrl`+`s` showing green success or failure. 

This plugin doesn't appear to do anything as far as I can tell. Atom behaves exactly the same with properly linted .yaml files as improperly formatted .yaml files.

**Comment by Arcanemagus** [comment]
Was the `linter` package installed for you? `linter-js-yaml` requires that to provide it's UI and run it. It _should_ have been automatically installed for you though...

**Comment by Arcanemagus** [comment]
Marking as closed since you haven't responded in 2 weeks. If you are still having issues though please let us know!
