### ISSUE TITLE
TypeError: Cannot read property 'rangeFromLineNumber' of undefined. 

### ISSUE THREAD

**Issue by jrquint** [AtomLinter/linter-js-yaml#24]
TypeError: Cannot read property 'rangeFromLineNumber' of undefined. 
error with EVERY new unindented line in YAML file.

at processMessage linter-js-yaml/lib/linter-js-yaml.js:57:25

**Comment by SpainTrain** [comment]
hmm, cannot reproduce.  Could you share the yaml file, as well as some info about your environment (atom version, plugin version, etc.)?  Thanks!

**Comment by mikechinaloy** [comment]
I'm also seeing the same problem (please find attach an example of a yaml file that throws this error). 

I'm using Atom version 1.2.4 with plugin version 1.2.4 on Mac OSX.

[Example.txt](https://github.com/AtomLinter/linter-js-yaml/files/53669/Example.txt)

**Comment by giseburt** [comment]
This is caused by atom-linter 3.4.0 getting installed. If I force it to use 3.3.7 by changing the package.json line

```json
    "atom-linter": "^3.3.7",
```

to be:

```json
    "atom-linter": "3.3.7",
```

and running amp install it will fix the issue.

**Comment by Arcanemagus** [comment]
Turns out this is due to a change in how `atom-linter` is exporting its functions, filed https://github.com/AtomLinter/atom-linter/issues/71 to track that. I'm putting up a PR that implements a method of importing that that works with both methods and will push out a release.

**Comment by Arcanemagus** [comment]
v1.2.5 pushed out that should fix this for everyone, let me know if there are any further issues.
