### ISSUE TITLE
Why is js-yaml pegged?

### ISSUE THREAD

**Issue by SpainTrain** [AtomLinter/linter-js-yaml#25]
Anyone know why js-yaml version is pinned?  If there's no reason, I will PR a fix.  If there is a reason, I will PR using npm-shrinkwrap =-D

**Comment by Arcanemagus** [comment]
It's been pinned since https://github.com/AtomLinter/linter-js-yaml/commit/df265168eb4af11f70d2c1589afe29658a963afb, last updated in https://github.com/AtomLinter/linter-js-yaml/commit/18630e769fb50948e6afa760106815959ac6fc79. No reasons given there though, trying to see anything in the issues.

**Comment by SpainTrain** [comment]
ty for indulging my laziness

**Comment by Arcanemagus** [comment]
@Adezandee or @eXprojects do either of you know the reasoning?

**Comment by Adezandee** [comment]
@Arcanemagus no specific reason, you can unpin it. I wonder if this is bad practice ?

**Comment by Arcanemagus** [comment]
It's actually better practice to peg the version since you are guaranteeing that it works and at the same time shielding yourself from any bugs introduced in the dependency in future versions.

At the same time though you are placing the burden of incorporating new versions entirely on yourself. Specifying it like `"^3.4.3"` places the trust in them to maintain a working release and to respect semver... which for the most part works fine which is why most packages use that.

**Comment by SpainTrain** [comment]
IMO pinning is never good practice, one should always use npm shrinkwrap - https://github.com/mishoo/UglifyJS2/pull/738#issuecomment-141563477 :-)

I think there is a valid argument for using npm shrinkwrap to ensure an apm linter package works properly, but it seems like it would apply equally to any linter plugin whose upstream linter is a node lib.  Unless of course the upstream is notorious for breaking releases, then shrinkwrapping is a no-brainer.

**Comment by SpainTrain** [comment]
Also, another option is http://greenkeeper.io/

**Comment by Arcanemagus** [comment]
greenkeeper looks awesome, enabling for this repo and another to test :wink:.

**Comment by SpainTrain** [comment]
Cool, the only downside to greenkeeper is that it won't lock recursive deps.  But if we are just concerned about js-yaml breaking that is probably fine.  And free services are nice :-)

**Comment by Arcanemagus** [comment]
Will save depending on somebody manually seeing that a dependency is out of date.

**Comment by SpainTrain** [comment]
for that I either use https://www.versioneye.com or https://david-dm.org

**Comment by Arcanemagus** [comment]
Yea, I've been using david-dm.org, but you need to actually look and see it is out of date for that to be useful, greenkeeper.io should notify us as soon as a new version gets released.

**Comment by Arcanemagus** [comment]
Ah, VersionEye has notification capabilities it looks like.
