### ISSUE TITLE
TypeError: Cannot read property 'rangeFromLineNumber' on undefined

### ISSUE THREAD

**Issue by alexec** [AtomLinter/linter-js-yaml#26]
With invalid YML, no error highlighting is show. Only large red error box:

![screen shot 2015-12-07 at 12 35 02](https://cloud.githubusercontent.com/assets/1142830/11626969/f45aa530-9cde-11e5-9906-792e39b96f1e.png)

~~~
$ atom -v
1.2.4
$ apm list|grep linter
├── linter@1.11.3
├── linter-js-yaml@1.2.4
├── linter-xmllint@1.1.0
~~~

**Comment by alexec** [comment]
Duplicate.

**Comment by Arcanemagus** [comment]
For clarity, this is a duplicate of #24. Although you actually posted the stack trace which is helpful, thanks!
